// Fixed skeleton structure per goal. Everything here is intentionally NOT
// generated by AI — a hypnotherapist should review and sign off on these
// exact words. Only the "suggestionPrompt" per goal is used to ask Claude
// to write the personalized middle section, constrained to fit the same
// slot every time.

const SKELETONS = {
  sleep: {
    induction:
      "Find a comfortable position, lying down, and when you're ready, let your eyes close. Take a slow breath in... and let it out, slower than it came in. Bring your attention to your feet. Let them go heavy and loose, and let that heaviness spread up through your ankles, your calves, your knees. With each breath out, you sink a little deeper into the bed beneath you.",
    deepener:
      "In a moment I'll count from ten down to one. With each number, you'll feel yourself drift twice as deep as before. Ten... settling in... nine... heavier... eight... seven... six... five... deeper now... four... three... two... almost there... one. You're exactly where you need to be.",
    emergence:
      "You don't need to do anything else now. Just let go, and let sleep take you the rest of the way.",
    suggestionPrompt:
      "Write ONE short paragraph (3-5 sentences, ~60-90 words) of sleep-hypnosis suggestion language, in second person, present tense, slow and soothing tone. It should gently address the person's specific worry described below, using their own words where natural, and reassure them that thoughts and worries can wait until morning. Never mention seeing a doctor, medication, or diagnosis. Never make guarantees about curing insomnia or anxiety. Do not include stage directions, headers, or anything except the paragraph itself.",
  },
  anxiety: {
    induction:
      "Find a spot to rest your eyes on, and as you keep looking at it, notice your breathing start to slow, all on its own. When your eyes feel ready, let them close. Breathe in for four counts, and out for six. Each breath out, your shoulders drop a little more.",
    deepener:
      "Picture a staircase in front of you, ten steps down, leading to a place that's completely yours: calm, quiet, safe. Ten... nine... going down... eight... seven... six... deeper and calmer... five... four... three... two... one. You've arrived.",
    emergence:
      "In a moment I'll count from one to five, and you'll return feeling calm, clear, and awake. One... coming back... two... energy returning to your body... three... aware of the room around you... four... eyes ready to open... five. Eyes open, fully awake, feeling calm and clear.",
    suggestionPrompt:
      "Write ONE short paragraph (3-5 sentences, ~60-90 words) of calming hypnosis suggestion language, second person, present tense. Gently reference the person's specific trigger and physical symptom described below, and offer a simple grounding reminder (e.g. returning to the breath). Never make medical claims, never promise to cure anxiety, never mention medication or diagnosis. No headers or stage directions, just the paragraph.",
  },
  confidence: {
    induction:
      "Get comfortable, and let your eyes close when you're ready. Take a breath in, and out, longer than it came in. Let your jaw soften, your shoulders drop, your hands rest, open and easy.",
    deepener:
      "Imagine stepping into an elevator, and as it moves downward, you relax more with every floor. Floor ten... relaxing... nine... eight... deeper... seven... six... five... four... three... two... one. Doors open onto a place that's calm, and completely yours.",
    emergence:
      "In a moment, count from one to five, returning fully alert, carrying this confidence with you. One... two, energy returning... three, aware of the room... four, eyes ready... five. Eyes open, confident, awake.",
    suggestionPrompt:
      "Write ONE short paragraph (3-5 sentences, ~60-90 words) of confidence-building hypnosis suggestion language, second person, present tense. Reference the specific situation and, if given, the self-doubt pattern described below, and reframe it gently. End on an empowering but realistic note (confidence coexisting with nerves, not eliminating them). No guarantees of success, no headers, just the paragraph.",
  },
  habit: {
    induction:
      "Settle into a comfortable position, and let your eyes close. Breathe in slowly, and out, even slower. Let go of any tension in your face, your neck, your hands.",
    deepener:
      "Count silently with me from ten to one, and with each number, relax twice as much as before. Ten... nine... eight... heavier... seven... six... five... four... three... two... one... completely at ease.",
    emergence:
      "Count from one to five, returning alert and steady. One... two... three, aware of your surroundings... four... five. Eyes open, clear, ready.",
    suggestionPrompt:
      "Write ONE short paragraph (3-5 sentences, ~60-90 words) of habit-change hypnosis suggestion language, second person, present tense. Reference the specific habit, the replacement behavior, and the stated motivation below. Frame it as a pause-and-choose moment, not willpower or shame. No guarantees, no medical claims, no headers, just the paragraph.",
  },
  focus: {
    induction:
      "Sit or lie comfortably, and let your eyes close. Breathe in, and out, slow and even. Let your shoulders release, your hands rest still.",
    deepener:
      "Count from five to one, relaxing more with each number. Five... four... three... two... one.",
    emergence:
      "Count from one to three, returning alert and focused. One... two... three. Eyes open, clear, ready to begin.",
    suggestionPrompt:
      "Write ONE short paragraph (3-5 sentences, ~50-80 words) of focus-hypnosis suggestion language, second person, present tense. Reference the specific task and distraction pattern below, and describe attention narrowing naturally to the task. No guarantees, no headers, just the paragraph.",
  },
  pain: {
    induction:
      "Find a position that's as comfortable as possible right now, and let your eyes close when you're ready. Take a slow breath in, and let it out, longer than it came in. Let your breathing find its own easy rhythm.",
    deepener:
      "Imagine warm water slowly rising around you, from your feet upward, each inch bringing more ease. Ten... nine... rising higher... eight... seven... six... five... four... three... two... one. Completely supported.",
    emergence:
      "In a moment, count from one to five, returning alert, carrying this ease with you. One... two... three, aware of the room... four... five. Eyes open, steady, calm.",
    suggestionPrompt:
      "Write ONE short paragraph (3-5 sentences, ~60-90 words) of hypnosis suggestion language for coping with discomfort, second person, present tense. Reference the area or type of discomfort described below. Use gentle imagery (warmth, distance, turning down a dial) for how the sensation can be experienced differently — NEVER claim the pain will disappear, be cured, or need no medical attention; frame it only as a way to relate to the sensation more calmly alongside their existing care. No headers, no medical claims, no guarantees, just the paragraph.",
  },
  motivation: {
    induction:
      "Get comfortable, and let your eyes close. Take a breath in, and let it out slowly. Let your shoulders soften, your hands rest easy.",
    deepener:
      "Count from ten to one, sinking a little deeper with each number. Ten... nine... eight... seven... six... five... four... three... two... one. Settled, and ready.",
    emergence:
      "Count from one to five, returning alert and energized. One... two... three, aware of the room... four... five. Eyes open, ready, motivated.",
    suggestionPrompt:
      "Write ONE short paragraph (3-5 sentences, ~60-90 words) of hypnosis suggestion language for motivation, second person, present tense. Reference the specific goal and the obstacle described below, and reframe starting as easy and small rather than requiring big willpower. No guarantees, no headers, just the paragraph.",
  },
  selfEsteem: {
    induction:
      "Settle into a comfortable position, and let your eyes close when you're ready. Take a slow breath in, and out. Let your body soften with each breath.",
    deepener:
      "Count from ten down to one, drifting a little deeper with each number. Ten... nine... eight... seven... six... five... four... three... two... one. Calm, and completely present.",
    emergence:
      "Count from one to five, returning alert, carrying this feeling with you. One... two... three... four... five. Eyes open, steady, at ease with yourself.",
    suggestionPrompt:
      "Write ONE short paragraph (3-5 sentences, ~60-90 words) of hypnosis suggestion language for general self-esteem, second person, present tense. Reference the specific self-critical pattern described below if given, and gently offer a kinder internal voice as an available choice, not a forced replacement. No guarantees, no headers, just the paragraph.",
  },
};

module.exports = { SKELETONS };
